In [1]:
import numpy as np

1. *text between one star will give itallic markdown* 
2. **text between two stars will make the text bold**
3. ***text between three stars will make the text bold and itallic***

There are 6 general mechanisms for creating arrays:

1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

***Examples of point number 1***

Creating a numpy 1D array below with the dtype. The dtype will decide how many bits of numerical can be allowed in the array eg. np.int8, np.int32, np.int64

In [2]:
myarray = np.array([3,4,5,6,7], np.int8)

In [3]:
myarray

array([3, 4, 5, 6, 7], dtype=int8)

Indexing in one dimensional array

In [4]:
myarray[0]

3

In order to create a 2D array one needs to put two square brackets.

In [5]:
myarray = np.array([[3,4,5,6,7]], np.int8)

In [6]:
myarray[0,0]

3

In [7]:
mylist_array = np.array([[1,2,3],[3,4,5],[6,7,8]])
mylist_array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

Changing a value in the numpy array

In [8]:
myarray[0,0]=8
myarray

array([[8, 4, 5, 6, 7]], dtype=int8)

**better to use integer and float dtype in creating a numpy array i.e. use only tuple and list with integer and float values to create a numpy array. Arrays can also be created by using dictionaries, sets and other python objects, but that is not a very efficient way of doing things. ***

***Examples of point number 2***

In [9]:
my_zeros = np.zeros((2,3))
my_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
my_ones = np.ones((5,6))
my_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

arange function of numpy is like range function of python. Here the atributes are start, stop and step.

In [11]:
my_range = np.arange(1,5,1)
my_range

array([1, 2, 3, 4])

linspace function of numpy will give linearly spaced values between a start and stop point. Attributes of this function are - start, stop and number of elements required in the output array. In the example below, 4 elements are printed which are linearly spaced between 2 and 7. 

In [12]:
my_linear_array = np.linspace(2,7,4)
my_linear_array

array([2.        , 3.66666667, 5.33333333, 7.        ])

np.empty() will create an empty array and fills it with random values. These values can be changed later on using index of the empty array

In [13]:
empty_array = np.empty((2,4))
empty_array

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306]])

In a simmilar fashion we can also create an empty array which has dimensions simmilar to other array which has already been created. use empty_like() for it.

In [14]:
emptylike_array = np.empty_like(my_linear_array)
emptylike_array

array([2.        , 3.66666667, 5.33333333, 7.        ])

We can create an identity marrtix or array using the identity function. np.identy(). Identity matrix is a square matrix and hence we need to pass only one value in the parenthesis not two. 

In [15]:
my_identity = np.identity((5))
my_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array_name.reshape() function reshapes the array to a specific shape which has been passed to it as an argument. 

In [16]:
reshaped_arryay = (np.arange(0,9,1)).reshape((3,3))
reshaped_arryay

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
new_array = np.array([[22,33,44],[55,66,77],[88,99,11]])

In [18]:
print(np.sqrt(new_array))

[[4.69041576 5.74456265 6.63324958]
 [7.41619849 8.1240384  8.77496439]
 [9.38083152 9.94987437 3.31662479]]


In [19]:
print(np.where(new_array>5))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


we can use array_name.ravel() to convert array of any shape to a 1 d array. 

In [20]:
x= reshaped_arryay.ravel()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
print(np.count_nonzero(new_array))

9


***Examples of point number 3***

In [22]:
reshaped_arryay

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
matrix_multiplication = reshaped_arryay*new_array
matrix_multiplication

array([[  0,  33,  88],
       [165, 264, 385],
       [528, 693,  88]])

In [24]:
matrix_sum = reshaped_arryay+new_array
matrix_sum

array([[ 22,  34,  46],
       [ 58,  70,  82],
       [ 94, 106,  19]])

**Important functions and attributes in Numpy - 
1. array.sum(), 
2. array.T, 
3. array.flat - (this will iterate through all the elements of an array.array) 
4. array.ndim - (this will give the numebr of dimensions of array)
5. array.size - (this will give the number of elements that are present in  the array. 
6. array.nbytes - (this will give us the number of bytes used by the array)
7. array.argmax() - (this will give the index value of the array where there is a maximum value)
8. array.argmin() - this will return the index of minimum value
9. array.argsort() - this will first sort an array and then return their index values. Gives out an array of indexes 
10. array.max()
11. array.min()
12. array.shape
13. array.size
14. array.dtype

In [25]:
myarray.shape

(1, 5)

In [26]:
myarray.size

5

In [27]:
myarray.dtype

dtype('int8')

In [28]:
y= (np.array([[3,4,5],[5,6,7],[8,9,0]])).sum(axis = 0)
y

array([16, 19, 12])

In [29]:
Transpose_array= (np.array([[3,4,5],[5,6,7],[8,9,0]])).T
Transpose_array

array([[3, 5, 8],
       [4, 6, 9],
       [5, 7, 0]])

In [30]:
for items in Transpose_array.flat:
    print(items)

3
5
8
4
6
9
5
7
0


In [31]:
print(Transpose_array.ndim)

2


In [32]:
print(Transpose_array.nbytes)

36


Documentation to find methods and attributes of numpy : 